### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by KOLANICH** [omnirom/android_packages_apps_OpenDelta#11]
Cyandelta shows a changelog for every version of CM, taken from github (now it doesn't show changelog for omnirom).
Why not to show a changelog for omnirom?

**Comment by sedrubal** [comment]
+1

**Comment by Madis0** [comment]
In my opinion, OpenDelta should have some kind of integration with OmniChange, the official changelog app.

For example:
- list commit names when an update is found according to filters defined in OmniChange 
- display a button `X CHANGES` next to FLASH/DOWNLOAD and CHECK, where X is a number of commits since last build 
- display a static button on the top bar to open OmniChange

**Comment by darkobas** [comment]
If you wanba upload a patch upload it to gerrit and we will review it
